<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Error</title>
    <style type="text/css">
        /*<![CDATA[*/       
        body {
            font: normal 9pt "Verdana";
            color: #000;
            background: #fff;
        }
        h1 {
            font: normal 18pt "Verdana";
            color: #f00;
            margin-bottom: .5em;
        }
        .container {
            margin: 1em 4em;
        }
        .time {
            color: gray;
            font-size: 8pt;
            border-top: 1px solid #aaa;
            padding-top: 1em;
            margin-bottom: 1em;
        }
        .message {
            color: #000;
            padding: 1em;
            font-size: 11pt;
            background: #f3f3f3;
            -webkit-border-radius: 10px;
            -moz-border-radius: 10px;
            border-radius: 10px;
            margin-bottom: 1em;
            line-height: 160%;
        }
        .source {
            margin-bottom: 1em;
        }
        .source .file {
            margin-bottom: 1em;
            font-weight: bold;
        }
        /*]]>*/
    </style>
</head>
<body>
<div class="container">
    <h1>Error</h1>
    <p class="message"><!--{$exception->getMessage()}--></p>
</div>
</body>
</html>
