<?php include APPLICATION_PATH . '/application/views/main.phtml';?>
<!--{extends file="main.phtml"}-->
<!--{block name='title'}--><!--{$title}--><!--{/block}-->
<!--{block name="body"}-->
<div class="easyui-layout" fit="true" id="rolepage" >        
<div region="center" style="border: none;width:500px;">
	<div class="easyui-layout" fit="true" id="left">
        <div region="center" style="border: none;">
            <table id="d_table" class="easyui-datagrid" fit="true" data-options="rownumbers:true,singleSelect:true,method:'get',toolbar:'#tp'"></table>
            <div id="m_div" class="easyui-dialog" data-options="closed:true,modal:true,onClose:clearForm" style="display: none;">
            	<div id="tp">
	                <a href="#" class="easyui-linkbutton" iconCls="icon-add" plain="true" onclick="javascript:openAdd()">新增</a>
	                <a href="#" class="easyui-linkbutton" iconCls="icon-add" plain="true" onclick="javascript:openCopy()">权限复制</a>
	            </div>   
                <div style="padding:10px 60px 20px 60px">
                    <form id="m_form">
                        <table cellpadding="5">
                            <tr>
                                <td>父项:</td>
                                <td><input id="m_frid" class="easyui-combotree" data-options="required:true,panelHeight:'200px',panelWidth:'220px'" name="pid" style="width:156px;"></td>
                            </tr>
                            <tr>
                                <td>角色名:</td>
                                <td><input class="easyui-textbox" type="text" name="name" data-options="required:true"/></td>
                            </tr>
                            <tr>
                                <td>序号:</td>
                                <td><input class="easyui-textbox" type="text" name="sort"/></td>
                            </tr>
                        </table>
                        <input type="hidden" name="id" id="m_id" value="">
                    </form>
                <div style="text-align:center;padding:5px">
                    <a class="easyui-linkbutton" iconCls="icon-ok" onclick="javascript:submitForm()" style="width:65px">提交</a>
                    <a class="easyui-linkbutton" iconCls="icon-cancel" onclick="javascript:$('#m_div').dialog('close')" style="width:65px">取消</a>
                </div>
                </div>
                
                <div id="m_copy_div" class="easyui-dialog" data-options="closed:true,modal:true,onClose:clearForm">
	                <div style="padding:10px 60px 20px 60px">
	                    <form id="m_copy_form">
	                        <table cellpadding="5">
	                            <tr>
	                                <td>源角色组:</td>
	                                <td><input id="m_s_frid" class="easyui-combotree" data-options="required:true,panelHeight:'200px',panelWidth:'220px'" name="source_role_id" style="width:156px;"></td>
	                            </tr>
	                            <tr>
	                                <td>目标角色组:</td>
	                                <td><input id="m_t_frid" class="easyui-combotree" data-options="required:true,panelHeight:'200px',panelWidth:'220px'" name="target_role_id" style="width:156px;"></td>
	                            </tr>                                
	                        </table>
	                    </form>
	                <div style="text-align:center;padding:5px">
	                    <a class="easyui-linkbutton" iconCls="icon-ok" onclick="javascript:submitCopyPrevilege()" style="width:65px">提交</a>
	                    <a class="easyui-linkbutton" iconCls="icon-cancel" onclick="javascript:$('#m_copy_div').dialog('close')" style="width:65px">取消</a>
	                </div>
	                </div>
	            </div>
                
            </div>   

        </div>                    
        
        <div region="south" style="height: 300px;">
            <div class="easyui-panel" fit="true" border="false" title="角色 → 用户">
                <table id="user_grid" class="easyui-datagrid" fit="true" style="width:700px;" data-options="rownumbers:true,singleSelect:false,method:'get',pagination:'true'"></table>
            </div>
        </div>
    </div>                 
</div>

<div title="权限设置【菜单 → 角色 ← 用户】" id="east" data-options="region:'east',split:true,collapsed:true" style="height:300px;width:400px">
    <div class="easyui-panel" fit="true" border="false" title="菜单">
        <table id="role_grid" class="easyui-datagrid">
            <ul id="role_menu" class="easyui-tree"></ul>
        </table>
    </div>
</div>            

</div>
<!--{/block}-->
<!--{block name='script'}-->
<script type="text/javascript" src="/public/js/role.js"></script>
<!--{/block}-->
</body>
</html>
