<!DOCTYPE html>
<html lang="en">
    <head>
    <meta charset="utf-8">
    <title><?php echo $title;?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta name="description" content="<!--{block name='desc'}--><!--{/block}-->"/>
	<meta name="author"  content="<!--{block name='author'}--><!--{/block}-->"/>
	<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <link rel="icon" href="/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" type="text/css" href="/public/themes/metro/easyui.css"/>
    <link rel="stylesheet" type="text/css" href="/public/themes/icon.css"/>
    <link rel="stylesheet" type="text/css" href="/public/themes/color.css"/>
    <link rel="stylesheet" type="text/css" href="/public/css/main.css"/>
    <link rel="stylesheet" type="text/css" href="/public/css/kube.css"/>
    <script type="text/javascript" src="/public/js/main.js"></script>
    <script type="text/javascript" src="/public/js/jquery-1.12.4.min.js"></script>
    <script type="text/javascript" src="/public/js/jquery.easyui.min.js"></script>
    <script type="text/javascript" src="/public/locale/easyui-lang-zh_CN.js"></script>
    <!--{block name='style'}--><!--{/block}-->
    </head>
    <body class="easyui-layout" style="overflow-y: hidden" scroll="no">
    <!--{block name='body'}--><!--{/block}-->
    <!--{block name='script'}--><!--{/block}-->
